### ISSUE TITLE
Begrensninger for ABC-kalkulator

### ISSUE THREAD

**Issue by KristianElde** [johanneherheim/personal-website#8]
ABC-kalkulator kan ikke regne ut komplekse røtter... krasjer ved input som kalkulerer til komplekse røtter.

**Comment by bocianowski1** [comment]
Hei! Denne burde gjøre susen:

https://abcc.fly.dev/

😁

**Comment by izaaksarnecki1** [comment]
@bocianowski1 Passende å foreslå micro-services?

**Comment by KristianElde** [comment]
Endelig! Har ventet på denne patchen i månedsvis nå! Gleder meg til å ta i bruk favoritt ABC-kalkulatoren min til komplekse utregninger igjen!
